<html>
<h1>Project 1B: Web Query Interface</h1>
<h4>Author: Ali Vala Barbaros<br />
UID: 704125620</h4>
<body>
Type an SQL query in the following box:
<p>
<form action="query.php" method="GET">
<textarea name="query" cols="60" rows="8"><?= isset($_GET["query"])?$_GET["query"]:'' ?></textarea>
<input type="submit" value="Submit" />
</form>
</p>
<p><small>Note: tables and fields are case sensitive. Run "show tables" to see the list of
available tables.</small>
</p>
</body>
</html>
<?php
//FUNCTIONS

//MySQL Connection Establishment function, and returns connection pointer
function est_db_connection(){
	$db_connection = mysql_connect("localhost","cs143","");

	//Check the connection is alive
	if(!$db_connection){
		$errmsg = mysql_error($db_connection);
		print "Connection failed:".$errmsg."<br />";
		exit(1);
	} 
	
	mysql_select_db("CS143",$db_connection);
	return $db_connection;
}

//Shutting down the MySQL connection after we all done.
function close_db_connection($db_connection){
	mysql_close($db_connection);
}

//Creating query according to the user input
function create_query($input,$db_connection){
	$rs = mysql_query($input,$db_connection);
	return $rs;
}

//Print out the result of the query as HTML table
function create_tableResult($rs){

	$numfields = mysql_num_fields($rs);//Number of attributes

	echo "<table border=1>";
	
	//First print out the attributes(column names)
	for ($index=0;$index<$numfields;$index++){
		echo "<th>".mysql_field_name($rs,$index)."</th>";
	}
	
	//Then print out all the results generated by the query
	while( $row = mysql_fetch_row($rs) ){

		echo "<tr>";
		for($r=0;$r<sizeof($row);$r++){
			if(Isset($row[$r]) != TRUE){//Check the field whether NULL or not
				 $row[$r]='N/A';//If NULL print N/A 
			}
			echo "<td align='center'>".$row[$r]."</td>";
		}
		echo "</tr>";
	}
	echo "</table>";
}

//MAIN 
if($_GET["query"]){

	ini_set('display_errors', 0); //NO PHP error messages

	$input = $_GET["query"];//Take input from textarea

	//Only SELECT and SHOW queries are allowed case insensetive	
	if(preg_match("/^\s*select/i",$input) or preg_match("/^\s*show/i",$input)){

		$db_connection = est_db_connection();//Establish connection with MySQL server

		echo "<h3>Results from MySQL:</h3>";	
	
		//Create query from user input.NO SANITIZING according to the specs of project
		$rs =  create_query($input,$db_connection);

		if (mysql_errno()) { 
  			echo mysql_error()."<br>"; 
		}
		else{
			//Print out query result
			create_tableResult($rs);
		}

		//Kill the connection after we all done
		close_db_connection($db_connection);

	}else{ echo "Sorry, only SELECT and SHOW queries are allowed!";}
}

?>

